<script setup>
const cart = useCartStore()
const form = reactive({ firstName: '', lastName: '', email: '', address: '', postalCode: '', city: '' })
const errorMessage = ref('')
const loading = ref(false)
const money = value => new Intl.NumberFormat('fr-FR', { style: 'currency', currency: 'EUR' }).format(value)
async function checkout() { loading.value = true; errorMessage.value = ''; try { const result = await $fetch('/api/checkout', { method: 'POST', body: { customer: form, items: cart.items.map(item => ({ id: item.id, quantity: item.quantity })) } }); await navigateTo(result.checkoutUrl, { external: true }) } catch (error) { errorMessage.value = error.data?.statusMessage || error.message || 'Le paiement est indisponible.' } finally { loading.value = false } }
</script>
<template><section class="mx-auto max-w-7xl px-5 py-10 sm:px-8 sm:py-12"><h1 class="font-serif text-4xl sm:text-5xl">Finaliser la commande</h1><form v-if="cart.items.length" class="mt-8 grid gap-8 lg:mt-10 lg:grid-cols-[1fr_.7fr] lg:gap-10" @submit.prevent="checkout"><div><h2 class="font-serif text-2xl sm:text-3xl">Vos coordonnées</h2><div class="mt-6 grid gap-4 sm:grid-cols-2"><input v-model="form.firstName" required placeholder="Prénom" class="w-full border p-4"><input v-model="form.lastName" required placeholder="Nom" class="w-full border p-4"><input v-model="form.email" required type="email" placeholder="E-mail" class="w-full border p-4 sm:col-span-2"><input v-model="form.address" required placeholder="Adresse" class="w-full border p-4 sm:col-span-2"><input v-model="form.postalCode" required placeholder="Code postal" class="w-full border p-4"><input v-model="form.city" required placeholder="Ville" class="w-full border p-4"></div></div><aside class="bg-[#f5eee6] p-5 sm:p-8"><h2 class="font-serif text-2xl sm:text-3xl">Votre écrin</h2><div class="my-6 border-y py-5"><div v-for="item in cart.items" :key="item.id" class="mb-3 flex justify-between gap-3 text-sm"><span>{{ item.name }} × {{ item.quantity }}</span><span class="shrink-0">{{ money(item.price * item.quantity) }}</span></div></div><div class="flex justify-between font-serif text-xl sm:text-2xl"><span>Total</span><span>{{ money(cart.total) }}</span></div><p v-if="errorMessage" class="mt-5 text-sm text-red-600">{{ errorMessage }}</p><button class="mt-6 w-full bg-[#302722] py-4 text-xs uppercase tracking-widest text-white" :disabled="loading">{{ loading ? 'Redirection…' : 'Payer avec Mollie' }}</button></aside></form><p v-else class="mt-10 text-sm">Votre panier est vide.</p></section></template>
